#!/usr/bin/perl -w

use PackageManager;

use UniLang::Agent::Agent;
use UniLang::Util::Message;

$UNIVERSAL::agent = UniLang::Agent::Agent->new
  (Name => "PackageManager",
   ReceiveHandler => \&Receive);
$UNIVERSAL::packagemanager = PackageManager->new();

sub Receive {
  my %args = @_;
  $UNIVERSAL::packagemanager->ProcessMessage
    (Message => $args{Message});
}

$UNIVERSAL::packagemanager->Execute();
